steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/flask-app-deployment', 'flask-app=gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
images:
- 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA'
substitutions:
  _ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'my-flask-cluster'

